/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MyLocksRouteImport } from './routes/my-locks'
import { Route as TokenMintRouteImport } from './routes/token.$mint'
import { Route as ApiPublicRpcRouteImport } from './routes/api/public/rpc'
import { Route as ApiPublicHooksClaimRewardsRouteImport } from './routes/api/public/hooks/claim-rewards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLocksRoute = MyLocksRouteImport.update({
  id: '/my-locks',
  path: '/my-locks',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenMintRoute = TokenMintRouteImport.update({
  id: '/token/$mint',
  path: '/token/$mint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRpcRoute = ApiPublicRpcRouteImport.update({
  id: '/api/public/rpc',
  path: '/api/public/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksClaimRewardsRoute =
  ApiPublicHooksClaimRewardsRouteImport.update({
    id: '/api/public/hooks/claim-rewards',
    path: '/api/public/hooks/claim-rewards',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launch': typeof LaunchRoute
  '/learn': typeof LearnRoute
  '/my-locks': typeof MyLocksRoute
  '/token/$mint': typeof TokenMintRoute
  '/api/public/rpc': typeof ApiPublicRpcRoute
  '/api/public/hooks/claim-rewards': typeof ApiPublicHooksClaimRewardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/launch': typeof LaunchRoute
  '/learn': typeof LearnRoute
  '/my-locks': typeof MyLocksRoute
  '/token/$mint': typeof TokenMintRoute
  '/api/public/rpc': typeof ApiPublicRpcRoute
  '/api/public/hooks/claim-rewards': typeof ApiPublicHooksClaimRewardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/launch': typeof LaunchRoute
  '/learn': typeof LearnRoute
  '/my-locks': typeof MyLocksRoute
  '/token/$mint': typeof TokenMintRoute
  '/api/public/rpc': typeof ApiPublicRpcRoute
  '/api/public/hooks/claim-rewards': typeof ApiPublicHooksClaimRewardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/launch'
    | '/learn'
    | '/my-locks'
    | '/token/$mint'
    | '/api/public/rpc'
    | '/api/public/hooks/claim-rewards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/launch'
    | '/learn'
    | '/my-locks'
    | '/token/$mint'
    | '/api/public/rpc'
    | '/api/public/hooks/claim-rewards'
  id:
    | '__root__'
    | '/'
    | '/launch'
    | '/learn'
    | '/my-locks'
    | '/token/$mint'
    | '/api/public/rpc'
    | '/api/public/hooks/claim-rewards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaunchRoute: typeof LaunchRoute
  LearnRoute: typeof LearnRoute
  MyLocksRoute: typeof MyLocksRoute
  TokenMintRoute: typeof TokenMintRoute
  ApiPublicRpcRoute: typeof ApiPublicRpcRoute
  ApiPublicHooksClaimRewardsRoute: typeof ApiPublicHooksClaimRewardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-locks': {
      id: '/my-locks'
      path: '/my-locks'
      fullPath: '/my-locks'
      preLoaderRoute: typeof MyLocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$mint': {
      id: '/token/$mint'
      path: '/token/$mint'
      fullPath: '/token/$mint'
      preLoaderRoute: typeof TokenMintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rpc': {
      id: '/api/public/rpc'
      path: '/api/public/rpc'
      fullPath: '/api/public/rpc'
      preLoaderRoute: typeof ApiPublicRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/claim-rewards': {
      id: '/api/public/hooks/claim-rewards'
      path: '/api/public/hooks/claim-rewards'
      fullPath: '/api/public/hooks/claim-rewards'
      preLoaderRoute: typeof ApiPublicHooksClaimRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaunchRoute: LaunchRoute,
  LearnRoute: LearnRoute,
  MyLocksRoute: MyLocksRoute,
  TokenMintRoute: TokenMintRoute,
  ApiPublicRpcRoute: ApiPublicRpcRoute,
  ApiPublicHooksClaimRewardsRoute: ApiPublicHooksClaimRewardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
